/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import static java.awt.PageAttributes.MediaType.A;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import static javafx.scene.input.KeyCode.A;
import static javafx.scene.input.KeyCode.F;
import javax.imageio.ImageIO;
import static javax.print.attribute.standard.MediaSize.Engineering.A;
import static javax.print.attribute.standard.MediaSizeName.A;
import static javax.swing.text.html.HTML.Tag.A;

/**
 *
 * @author moham
 */
public class Impression extends javax.swing.JFrame {
    
    /**
     * Creates new form Accueil
     */
    /*JFrame frame = new JFrame();
    URL url = getClass().getResource("icon.png");
    ImageIcon imgicon = new ImageIcon(url);
    frame.setIconImage(imgicon.getImage());*/
    
    Timer updateTimer;
    int Delay = 100;
    public Impression() {
        initComponents();
        this.setLocationRelativeTo(null);
        updateTimer = new Timer(Delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date currentTime = new Date();
                String formatTimerStr = "hh:mm:ss a";
                DateFormat formatTime = new SimpleDateFormat(formatTimerStr);
                String FormattedTimeStr = formatTime.format(currentTime);
                jLabel12.setText(FormattedTimeStr);
            }
        });
          updateTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        ht = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        tva = new javax.swing.JLabel();
        date_ = new javax.swing.JLabel();
        nb_g = new javax.swing.JLabel();
        nb_s = new javax.swing.JLabel();
        nb_j = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/icon.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ht.setText("jLabel2");
        getContentPane().add(ht, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        client.setText("jLabel2");
        getContentPane().add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 326, 270, 20));

        total.setText("jLabel13");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, -1, -1));

        tva.setText("jLabel10");
        getContentPane().add(tva, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        date_.setText("jLabel7");
        getContentPane().add(date_, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 140, 10));

        nb_g.setText("jLabel2");
        getContentPane().add(nb_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        nb_s.setText("jLabel6");
        getContentPane().add(nb_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        nb_j.setText("jLabel5");
        getContentPane().add(nb_j, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/1.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 19, 620, 860));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/close_icon.png"))); // NOI18N
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1359, 10, 42, 44);

        kButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/pdf_icon.png"))); // NOI18N
        kButton3.setText("Télécharger Facture");
        kButton3.setEnabled(false);
        kButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        kButton3.setIconTextGap(30);
        kButton3.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        kButton3.setkEndColor(new java.awt.Color(0, 0, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 102, 0));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        kButton3.setkStartColor(new java.awt.Color(0, 0, 0));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3);
        kButton3.setBounds(260, 900, 381, 70);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/reduce_icon.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1305, 10, 42, 44);

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(758, 10, 0, 0);

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/reduce_icon.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(800, 10, 44, 44);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_/close_icon.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(850, 10, 40, 44);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection c = cnx.connect();
            Statement st = c.createStatement();
            String sql = "select nb_g,nb_j,nb_s,p_g,p_j,p_s,tva,client,(nb_g*p_g)+(nb_j*p_j)+(nb_s*p_s),((nb_g*p_g)+(nb_j*p_j)+(nb_s*p_s))+tva from factures where id=(select max(id) from factures)";
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                client.setText(rs.getString(8));
                
                nb_g.setText(rs.getString(1));
                nb_j.setText(rs.getString(2));
                nb_s.setText(rs.getString(3));
                
                tva.setText(rs.getString(7));
                ht.setText(rs.getString(9));
                total.setText(rs.getString(10));
                
                Date currentTime = new Date();
                String formatTimerStr = "dd-MM-YYYY";
                DateFormat formatTime = new SimpleDateFormat(formatTimerStr);
                String FormattedTimeStr = formatTime.format(currentTime);
                date_.setText(FormattedTimeStr);
                        
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int desicion = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment quitter!","Confirmation",JOptionPane.YES_NO_OPTION);
        if (desicion==JOptionPane.YES_OPTION) {
            this.dispose();
        }else{
            this.setVisible(true);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(Impression.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        
    }//GEN-LAST:event_kButton3ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.setState(impression_factures.ICONIFIED);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int desicion = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment quitter!","Confirmation",JOptionPane.YES_NO_OPTION);
        if (desicion==JOptionPane.YES_OPTION) {
            this.dispose();
        }else{
            this.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked
    int count = 1;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impression().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel client;
    private javax.swing.JLabel date_;
    private javax.swing.JLabel ht;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel nb_g;
    private javax.swing.JLabel nb_j;
    private javax.swing.JLabel nb_s;
    private javax.swing.JLabel total;
    private javax.swing.JLabel tva;
    // End of variables declaration//GEN-END:variables
}
